# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: arduino/setup-arduino-cli@v1.0.0
      with:
        version: '0.6.x'
    - name: Install ESP32
      run: |
        arduino-cli core update-index --additional-urls 'https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json'
        arduino-cli core install esp32:esp32 --additional-urls 'https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json'
        #esp32:esp32:featheresp32
        arduino-cli lib install "Adafruit NeoPixel" --additional-urls 'https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json'
        arduino-cli lib install "BLEPeripheral" --additional-urls 'https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json'
        python -m pip install pyserial
        python3 -m pip install pyserial
    - name: Test compiling
      run: |
        for INOS in $(pwd | find -print | grep ino)
        do
          echo "Compiling $INOS"
          arduino-cli compile -b esp32:esp32:featheresp32 $INOS
        done
